### ISSUE TITLE
Tracking: Implement WebDAV Push

### ISSUE THREAD

**Issue by lennart-k** [lennart-k/rustical#8]
See https://github.com/bitfireAT/webdav-push/
- [x] `topic` and `transports` properties
- [x] `subscriptions` endpoint
- [x] subscription registration, addressed in 5b418ec583ae7ed86bf0a983508e3b19ad12526b
- [x] Push events on changes
- [x] Configurable allow-lists for UP domains
- [x] Refactoring
- [x] CalDAV Push support
- [x] CardDAV Push support (implemented in 751c2d1ce70e346e18e910a2f16b325ba41079d2)

**Comment by lennart-k** [comment]
Rudimentary support implemented in 347061ff8fa9bbaa10852e1eb598ecde525452f6
